//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export class ApiClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://api.anurag.sh/maccas/v1";

    }

    /**
     * @return List of currently locked deals
     */
    get_locked_deals( cancelToken?: CancelToken | undefined): Promise<ApiResponse<string[]>> {
        let url_ = this.baseUrl + "/admin/locked-deals";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_locked_deals(_response);
        });
    }

    protected processGet_locked_deals(response: AxiosResponse): Promise<ApiResponse<string[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<string[]>>(new ApiResponse<string[]>(status, _headers, result200));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<string[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @param duration (optional) 
     * @return Lock this deal
     */
    lock_deal(deal_id: string, duration?: number | null | undefined, cancelToken?: CancelToken | undefined): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/admin/locked-deals/{deal_id}?";
        if (deal_id === undefined || deal_id === null)
            throw new Error("The parameter 'deal_id' must be defined.");
        url_ = url_.replace("{deal_id}", encodeURIComponent("" + deal_id));
        if (duration !== undefined && duration !== null)
            url_ += "duration=" + encodeURIComponent("" + duration) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processLock_deal(_response);
        });
    }

    protected processLock_deal(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Unlocked deal
     */
    unlock_deal(deal_id: string, cancelToken?: CancelToken | undefined): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/admin/locked-deals/{deal_id}";
        if (deal_id === undefined || deal_id === null)
            throw new Error("The parameter 'deal_id' must be defined.");
        url_ = url_.replace("{deal_id}", encodeURIComponent("" + deal_id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUnlock_deal(_response);
        });
    }

    protected processUnlock_deal(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return List of currently locked deals
     */
    get_all_user_spending( cancelToken?: CancelToken | undefined): Promise<ApiResponse<{ [key: string]: AdminUserSpending; }>> {
        let url_ = this.baseUrl + "/admin/user/spending";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_all_user_spending(_response);
        });
    }

    protected processGet_all_user_spending(response: AxiosResponse): Promise<ApiResponse<{ [key: string]: AdminUserSpending; }>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<{ [key: string]: AdminUserSpending; }>>(new ApiResponse<{ [key: string]: AdminUserSpending; }>(status, _headers, result200));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<{ [key: string]: AdminUserSpending; }>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Random code for specified deal
     */
    get_code(deal_id: string, store: string, cancelToken?: CancelToken | undefined): Promise<ApiResponse<OfferResponse>> {
        let url_ = this.baseUrl + "/code/{deal_id}?";
        if (deal_id === undefined || deal_id === null)
            throw new Error("The parameter 'deal_id' must be defined.");
        url_ = url_.replace("{deal_id}", encodeURIComponent("" + deal_id));
        if (store === undefined || store === null)
            throw new Error("The parameter 'store' must be defined and cannot be null.");
        else
            url_ += "store=" + encodeURIComponent("" + store) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_code(_response);
        });
    }

    protected processGet_code(response: AxiosResponse): Promise<ApiResponse<OfferResponse>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<OfferResponse>>(new ApiResponse<OfferResponse>(status, _headers, result200));

        } else if (status === 404) {
            const _responseText = response.data;
            return throwException("Deal not found", status, _responseText, _headers);

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<OfferResponse>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return List of available deals
     */
    get_deals( cancelToken?: CancelToken | undefined): Promise<ApiResponse<GetDealsOffer[]>> {
        let url_ = this.baseUrl + "/deals";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_deals(_response);
        });
    }

    protected processGet_deals(response: AxiosResponse): Promise<ApiResponse<GetDealsOffer[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<GetDealsOffer[]>>(new ApiResponse<GetDealsOffer[]>(status, _headers, result200));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<GetDealsOffer[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Last Refresh of Cache
     */
    get_last_refresh( cancelToken?: CancelToken | undefined): Promise<ApiResponse<LastRefreshInformation>> {
        let url_ = this.baseUrl + "/deals/last-refresh";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_last_refresh(_response);
        });
    }

    protected processGet_last_refresh(response: AxiosResponse): Promise<ApiResponse<LastRefreshInformation>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<LastRefreshInformation>>(new ApiResponse<LastRefreshInformation>(status, _headers, result200));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<LastRefreshInformation>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Information for specified deal
     */
    get_deal(deal_id: string, cancelToken?: CancelToken | undefined): Promise<ApiResponse<GetDealsOffer>> {
        let url_ = this.baseUrl + "/deals/{deal_id}";
        if (deal_id === undefined || deal_id === null)
            throw new Error("The parameter 'deal_id' must be defined.");
        url_ = url_.replace("{deal_id}", encodeURIComponent("" + deal_id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_deal(_response);
        });
    }

    protected processGet_deal(response: AxiosResponse): Promise<ApiResponse<GetDealsOffer>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<GetDealsOffer>>(new ApiResponse<GetDealsOffer>(status, _headers, result200));

        } else if (status === 404) {
            const _responseText = response.data;
            return throwException("Deal not found", status, _responseText, _headers);

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<GetDealsOffer>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Added a deal
     */
    add_deal(deal_id: string, store: string, cancelToken?: CancelToken | undefined): Promise<ApiResponse<OfferResponse>> {
        let url_ = this.baseUrl + "/deals/{deal_id}?";
        if (deal_id === undefined || deal_id === null)
            throw new Error("The parameter 'deal_id' must be defined.");
        url_ = url_.replace("{deal_id}", encodeURIComponent("" + deal_id));
        if (store === undefined || store === null)
            throw new Error("The parameter 'store' must be defined and cannot be null.");
        else
            url_ += "store=" + encodeURIComponent("" + store) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAdd_deal(_response);
        });
    }

    protected processAdd_deal(response: AxiosResponse): Promise<ApiResponse<OfferResponse>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<OfferResponse>>(new ApiResponse<OfferResponse>(status, _headers, result200));

        } else if (status === 400) {
            const _responseText = response.data;
            return throwException("Error on McDonald\'s side", status, _responseText, _headers);

        } else if (status === 404) {
            const _responseText = response.data;
            return throwException("Deal not found", status, _responseText, _headers);

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<OfferResponse>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Removed a deal
     */
    remove_deal(deal_id: string, store: string, cancelToken?: CancelToken | undefined): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/deals/{deal_id}?";
        if (deal_id === undefined || deal_id === null)
            throw new Error("The parameter 'deal_id' must be defined.");
        url_ = url_.replace("{deal_id}", encodeURIComponent("" + deal_id));
        if (store === undefined || store === null)
            throw new Error("The parameter 'store' must be defined and cannot be null.");
        else
            url_ += "store=" + encodeURIComponent("" + store) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRemove_deal(_response);
        });
    }

    protected processRemove_deal(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 400) {
            const _responseText = response.data;
            return throwException("Error on McDonald\'s side", status, _responseText, _headers);

        } else if (status === 404) {
            const _responseText = response.data;
            return throwException("Deal not found", status, _responseText, _headers);

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return JSON OpenApi spec
     */
    get_openapi( cancelToken?: CancelToken | undefined): Promise<ApiResponse<string>> {
        let url_ = this.baseUrl + "/docs/openapi";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_openapi(_response);
        });
    }

    protected processGet_openapi(response: AxiosResponse): Promise<ApiResponse<string>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<ApiResponse<string>>(new ApiResponse<string>(status, _headers, result200));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<string>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Server is healthy
     */
    get_status( cancelToken?: CancelToken | undefined): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/health/status";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_status(_response);
        });
    }

    protected processGet_status(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return List of locations near specified coordinates
     */
    get_locations(distance: number, latitude: number, longitude: number, cancelToken?: CancelToken | undefined): Promise<ApiResponse<RestaurantInformation[]>> {
        let url_ = this.baseUrl + "/locations?";
        if (distance === undefined || distance === null)
            throw new Error("The parameter 'distance' must be defined and cannot be null.");
        else
            url_ += "distance=" + encodeURIComponent("" + distance) + "&";
        if (latitude === undefined || latitude === null)
            throw new Error("The parameter 'latitude' must be defined and cannot be null.");
        else
            url_ += "latitude=" + encodeURIComponent("" + latitude) + "&";
        if (longitude === undefined || longitude === null)
            throw new Error("The parameter 'longitude' must be defined and cannot be null.");
        else
            url_ += "longitude=" + encodeURIComponent("" + longitude) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_locations(_response);
        });
    }

    protected processGet_locations(response: AxiosResponse): Promise<ApiResponse<RestaurantInformation[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<RestaurantInformation[]>>(new ApiResponse<RestaurantInformation[]>(status, _headers, result200));

        } else if (status === 400) {
            const _responseText = response.data;
            return throwException("Invalid/missing parameters", status, _responseText, _headers);

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<RestaurantInformation[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Closest location near specified text
     */
    search_locations(text: string, cancelToken?: CancelToken | undefined): Promise<ApiResponse<RestaurantInformation>> {
        let url_ = this.baseUrl + "/locations/search?";
        if (text === undefined || text === null)
            throw new Error("The parameter 'text' must be defined and cannot be null.");
        else
            url_ += "text=" + encodeURIComponent("" + text) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processSearch_locations(_response);
        });
    }

    protected processSearch_locations(response: AxiosResponse): Promise<ApiResponse<RestaurantInformation>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<RestaurantInformation>>(new ApiResponse<RestaurantInformation>(status, _headers, result200));

        } else if (status === 404) {
            const _responseText = response.data;
            return throwException("No locations found", status, _responseText, _headers);

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<RestaurantInformation>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return List of all account points
     */
    get_points( cancelToken?: CancelToken | undefined): Promise<ApiResponse<AccountPointMap[]>> {
        let url_ = this.baseUrl + "/points";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_points(_response);
        });
    }

    protected processGet_points(response: AxiosResponse): Promise<ApiResponse<AccountPointMap[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<AccountPointMap[]>>(new ApiResponse<AccountPointMap[]>(status, _headers, result200));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<AccountPointMap[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Random code for account
     */
    get_points_by_id(account_id: string, store: string, cancelToken?: CancelToken | undefined): Promise<ApiResponse<OfferPointsResponse>> {
        let url_ = this.baseUrl + "/points/{account_id}?";
        if (account_id === undefined || account_id === null)
            throw new Error("The parameter 'account_id' must be defined.");
        url_ = url_.replace("{account_id}", encodeURIComponent("" + account_id));
        if (store === undefined || store === null)
            throw new Error("The parameter 'store' must be defined and cannot be null.");
        else
            url_ += "store=" + encodeURIComponent("" + store) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_points_by_id(_response);
        });
    }

    protected processGet_points_by_id(response: AxiosResponse): Promise<ApiResponse<OfferPointsResponse>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<OfferPointsResponse>>(new ApiResponse<OfferPointsResponse>(status, _headers, result200));

        } else if (status === 404) {
            const _responseText = response.data;
            return throwException("Account not found", status, _responseText, _headers);

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<OfferPointsResponse>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Account statistics
     */
    get_accounts( cancelToken?: CancelToken | undefined): Promise<ApiResponse<{ [key: string]: number; }>> {
        let url_ = this.baseUrl + "/statistics/account";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_accounts(_response);
        });
    }

    protected processGet_accounts(response: AxiosResponse): Promise<ApiResponse<{ [key: string]: number; }>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<{ [key: string]: number; }>>(new ApiResponse<{ [key: string]: number; }>(status, _headers, result200));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<{ [key: string]: number; }>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Total account count
     */
    get_total_accounts( cancelToken?: CancelToken | undefined): Promise<ApiResponse<number>> {
        let url_ = this.baseUrl + "/statistics/total-accounts";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_total_accounts(_response);
        });
    }

    protected processGet_total_accounts(response: AxiosResponse): Promise<ApiResponse<number>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<ApiResponse<number>>(new ApiResponse<number>(status, _headers, result200));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<number>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Config for current user
     */
    get_user_config( cancelToken?: CancelToken | undefined): Promise<ApiResponse<UserOptions>> {
        let url_ = this.baseUrl + "/user/config";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_user_config(_response);
        });
    }

    protected processGet_user_config(response: AxiosResponse): Promise<ApiResponse<UserOptions>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<UserOptions>>(new ApiResponse<UserOptions>(status, _headers, result200));

        } else if (status === 404) {
            const _responseText = response.data;
            return throwException("No config for this user", status, _responseText, _headers);

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<UserOptions>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Updated/created config
     */
    update_user_config(body: UserOptions, cancelToken?: CancelToken | undefined): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/user/config";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUpdate_user_config(_response);
        });
    }

    protected processUpdate_user_config(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 400) {
            const _responseText = response.data;
            return throwException("Invalid configuration format", status, _responseText, _headers);

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return Spending information for this user
     */
    get_user_spending( cancelToken?: CancelToken | undefined): Promise<ApiResponse<UserSpending>> {
        let url_ = this.baseUrl + "/user/spending";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_user_spending(_response);
        });
    }

    protected processGet_user_spending(response: AxiosResponse): Promise<ApiResponse<UserSpending>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<UserSpending>>(new ApiResponse<UserSpending>(status, _headers, result200));

        } else if (status === 500) {
            const _responseText = response.data;
            return throwException("Internal Server Error", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<UserSpending>>(new ApiResponse(status, _headers, null as any));
    }
}

export interface AccountPointMap {
    name: string;
    totalPoints: number;

    [key: string]: any;
}

export interface AccountResponse {

    [key: string]: number | any;
}

export interface AdminUserSpending {
    items: GetDealsOffer[];
    name: string;
    total: number;

    [key: string]: any;
}

export interface AdminUserSpendingMap {

    [key: string]: AdminUserSpending | any;
}

export interface GetDealsOffer {
    count: number;
    creationDateUtc: string;
    dealUuid: string;
    description: string;
    imageUrl: string;
    name: string;
    price?: number | undefined;
    shortName: string;
    validFromUtc: string;
    validToUtc: string;

    [key: string]: any;
}

export interface LastRefreshInformation {
    lastRefresh: string;

    [key: string]: any;
}

export interface OfferPointsResponse {
    offerResponse: OfferResponse;
    pointsResponse: PointsResponse;

    [key: string]: any;
}

export interface OfferResponse {
    message: string;
    randomCode: string;

    [key: string]: any;
}

export interface PointsResponse {
    lifeTimePoints: number;
    totalPoints: number;

    [key: string]: any;
}

export interface RestaurantAddress {
    addressLine: string;

    [key: string]: any;
}

export interface RestaurantInformation {
    address: RestaurantAddress;
    name: string;
    storeNumber: number;

    [key: string]: any;
}

export interface UserOptions {
    storeId: string;
    storeName?: string | undefined;

    [key: string]: any;
}

export interface UserSpending {
    items: GetDealsOffer[];
    total: number;

    [key: string]: any;
}

function jsonParse(json: any, reviver?: any) {
    json = JSON.parse(json, reviver);

    var byid: any = {};
    var refs: any = [];
    json = (function recurse(obj: any, prop?: any, parent?: any) {
        if (typeof obj !== 'object' || !obj)
            return obj;
        
        if ("$ref" in obj) {
            let ref = obj.$ref;
            if (ref in byid)
                return byid[ref];
            refs.push([parent, prop, ref]);
            return undefined;
        } else if ("$id" in obj) {
            let id = obj.$id;
            delete obj.$id;
            if ("$values" in obj)
                obj = obj.$values;
            byid[id] = obj;
        }
        
        if (Array.isArray(obj)) {
            obj = obj.map((v, i) => recurse(v, i, obj));
        } else {
            for (var p in obj) {
                if (obj.hasOwnProperty(p) && obj[p] && typeof obj[p] === 'object')
                    obj[p] = recurse(obj[p], p, obj);
            }
        }

        return obj;
    })(json);

    for (let i = 0; i < refs.length; i++) {
        const ref = refs[i];
        ref[0][ref[1]] = byid[ref[2]];
    }

    return json;
}

function createInstance<T>(data: any, mappings: any, type: any): T | null {
  if (!mappings)
    mappings = [];
  if (!data)
    return null;

  const mappingIndexName = "__mappingIndex";
  if (data[mappingIndexName])
    return <T>mappings[data[mappingIndexName]].target;

  data[mappingIndexName] = mappings.length;

  let result: any = new type();
  mappings.push({ source: data, target: result });
  result.init(data, mappings);
  return result;
}

export class ApiResponse<TResult> {
    status: number;
    headers: { [key: string]: any; };
    result: TResult;

    constructor(status: number, headers: { [key: string]: any; }, result: TResult)
    {
        this.status = status;
        this.headers = headers;
        this.result = result;
    }
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new ApiException(message, status, response, headers, result);
}

function isAxiosError(obj: any | undefined): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}