// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface JwtClaim { exp: bigint, nbf: bigint, ver: string, iss: string, sub: string, aud: string, nonce: string, iat: bigint, oid: string, name: string, tfp: string, }