// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfferResponse } from "./OfferResponse";
import type { PointsResponse } from "./PointsResponse";

export interface OfferPointsResponse { offerResponse: OfferResponse, pointsResponse: PointsResponse, }